### ISSUE TITLE
[feat]#1 CI/CD 파이프라인 구축

### ISSUE THREAD

**Issue by seokjun01** [Leets-Official/X-BE#1]
## 1. 무엇을?

<br> CI/CD 파이프라인을 설정하여 코드 푸시 시 자동으로 빌드 및 배포가 이루어지도록 한다

## 2. 상세 설명

<br>

**Comment by hyxklee** [comment]
이슈 제목은 [feat] #1 CI/CD 파이프라인 구축  으로 해주시면 됩니당😄
브랜치명은 feat/#1/CI/CD-파이프라인-구축  으로 해주시면 됩니당
해당 컨벤션은 프로젝트 전반에 걸쳐 통일된 내용이니 숙지해주시면 좋습니닷

또한 이슈 우측에 Assignees에 assingn yourself를 해서 해당 이슈의 작업자가 본인임을 밝혀주세요!
그리고 Lables를 선택해 해당 이슈가 어떤 작업인지 다시 한번 강조해 주시면 좋습니다!

**Comment by hyxklee** [comment]
작업 완료된 이슈는 PR이 머지됨과 같이 닫아주세요!
